version: "3.0"

networks:
  my-networks:
    driver: bridge
    name: getting-started #networks_name
    ipam:
      driver: default
      config:
        - subnet: 192.168.121.0/24
          gateway: 192.168.121.1

services:
  getting-started:
    image: docker/getting-started:latest
    container_name: getting-started
    networks:
      my-networks:
        ipv4_address: 192.168.121.2 #static_ip
    ports:
      - 8880:80
    restart: unless-stopped
